server:
  port: 8083

spring:
  application:
    name: auth-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: auth-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: thisIsTheSecretKeywhichIsAtLeast32CharactersLong
  expiration: 1800000

logging:
  level:
    org.springframework.kafka: INFO
    org.apache.kafka: INFO